Integrate database
NCAR/chemistry-cafe pull request #49
Opened 2024-10-30 22:44 UTC by oreogunleye24

The database, frontend, and backend run in a containerized Docker environment.
All backend models, controllers, and services were adjusted to work with the new database structure. 
Adjusted all the frontend APIs
Fixed some design issues.

2024-10-31 14:07 UTC, K20shores requested changes
Just a few comments from my brief review.

2024-10-31 14:07 UTC, K20shores commented on backend/Models/Family.cs
> +    public int Id { get; set; }
I have a preference for primary keys to be Guids, as the students did before. Can you make that change here and for all other classes?

2024-10-31 14:07 UTC, K20shores commented on backend/Models/ReactionSpecies.cs
> +    public virtual Species Species { get; set; } = null!;
`reaction_id`, `species_id` seem to be duplicates of `ReactionId` and `SpeciesId`, why? Also, why do we need this file and `Species.cs`?

2024-10-31 20:19 UTC, oreogunleye24 commented on backend/Models/ReactionSpecies.cs
> +    public virtual Species Species { get; set; } = null!;
No, those just say that we have foreign keys in the file. The foreign keys are the reaction_id and the species_id which come from the reaction and species table.

2024-10-31 20:20 UTC, oreogunleye24 commented on backend/Models/Reaction.cs
> +    public string Equation { get; set; } = null!;
Equation is basically the reaction string.

2024-10-31 20:20 UTC, oreogunleye24 commented on backend/Models/Family.cs
> +    public int Id { get; set; }
Sure, I'll make that change.

2024-11-01 12:15 UTC, K20shores commented on backend/Models/Reaction.cs
> +    public string Equation { get; set; } = null!;
That's not something I'm expecting, especially if it's something we later parse. What do we gain from storing the equation?

2024-11-01 19:50 UTC, oreogunleye24 commented on backend/Models/Reaction.cs
> +    public string Equation { get; set; } = null!;
We need to know what species are involved in the reaction. This information also helps us display the reactions associated with mechanisms and families on the front page.
All the reactions, species, and families I have in the database right now are from this link you gave us: https://github.com/NCAR/music-box/tree/main/src/acom_music_box/examples/configs/ts1

2024-11-04 15:18 UTC, K20shores commented on backend/Models/Reaction.cs
> +    public string Equation { get; set; } = null!;
Right, the species and products of a reaction should not be something that we parse. It should be a relation in the database. I believe that's how the students set it up last semester. I am fine with a more flat database structure with fewer tables, but list relationships still need to be maintained

2024-11-04 19:46 UTC, oreogunleye24 commented on backend/Models/Reaction.cs
> +    public string Equation { get; set; } = null!;
Okay that's fine, I will adjust it.

2024-11-05 02:09 UTC, merged